/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation;

import command.CreateDatabaseCommand;
import command.CreateTableCommand;
import command.DisplayDataCommand;
import command.InsertDataCommand;
import controller.DatabaseController;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Stock;
import repository.DatabaseRepository;
import repository.SqlServerDatabaseRepository;
import service.DatabaseService;

/**
 *
 * @author ADMIN
 */
public class CreateDatabaseFrame extends javax.swing.JFrame {

    private final DatabaseController controller;

    /**
     * Creates new form CreateDatabaseFrame
     */
    public CreateDatabaseFrame() {
        initComponents();

        DatabaseRepository repository
                = new SqlServerDatabaseRepository();

        DatabaseService service
                = new DatabaseService(repository);

        CreateDatabaseCommand createDatabaseCommand
                = new CreateDatabaseCommand(service);

        CreateTableCommand createTableCommand
                = new CreateTableCommand(service);

        InsertDataCommand insertDataCommand
                = new InsertDataCommand(service);

        DisplayDataCommand displayDataCommand
                = new DisplayDataCommand(service);

        controller = new DatabaseController(
                createDatabaseCommand,
                createTableCommand,
                insertDataCommand,
                displayDataCommand
        );

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStocks = new javax.swing.JTable();
        btnCreateTable = new javax.swing.JButton();
        btnCreateDatabase = new javax.swing.JButton();
        btnInsertData = new javax.swing.JButton();
        btnDisplayData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Database");
        setMinimumSize(new java.awt.Dimension(500, 400));

        tblStocks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "StockID", "StockName", "Address", "DateAvailable", "Note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStocks);

        btnCreateTable.setText("Create table");
        btnCreateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTableActionPerformed(evt);
            }
        });

        btnCreateDatabase.setText("Create DB");
        btnCreateDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDatabaseActionPerformed(evt);
            }
        });

        btnInsertData.setText("Insert data");
        btnInsertData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertDataActionPerformed(evt);
            }
        });

        btnDisplayData.setText("Display data");
        btnDisplayData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCreateDatabase)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreateTable)
                        .addGap(18, 18, 18)
                        .addComponent(btnInsertData)
                        .addGap(18, 18, 18)
                        .addComponent(btnDisplayData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplayData)
                    .addComponent(btnInsertData)
                    .addComponent(btnCreateTable)
                    .addComponent(btnCreateDatabase))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTableActionPerformed
        try {
            controller.createTable();

            JOptionPane.showMessageDialog(
                    this,
                    "Table Stocks created successfully!"
            );

        } catch (SQLException exception) {
            showError(exception);
        }
    }//GEN-LAST:event_btnCreateTableActionPerformed

    private void btnCreateDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDatabaseActionPerformed
        try {
            controller.createDatabase();

            JOptionPane.showMessageDialog(
                    this,
                    "Database FU_DB created successfully!"
            );

        } catch (SQLException exception) {
            showError(exception);
        }
    }//GEN-LAST:event_btnCreateDatabaseActionPerformed

    private void btnInsertDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertDataActionPerformed
        try {
            controller.insertData();

            JOptionPane.showMessageDialog(
                    this,
                    "Five stocks inserted successfully!"
            );

        } catch (SQLException exception) {
            showError(exception);
        }
    }//GEN-LAST:event_btnInsertDataActionPerformed

    private void btnDisplayDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayDataActionPerformed
        try {
            List<Stock> stocks = controller.displayData();
            displayStocks(stocks);

        } catch (SQLException exception) {
            showError(exception);
        }
    }//GEN-LAST:event_btnDisplayDataActionPerformed

    private void displayStocks(List<Stock> stocks) {
    DefaultTableModel model =
            (DefaultTableModel) tblStocks.getModel();

    DateTimeFormatter formatter =
            DateTimeFormatter.ofPattern("dd/MM/yyyy");

    model.setRowCount(0);

    for (Stock stock : stocks) {
        model.addRow(new Object[]{
            stock.getStockID(),
            stock.getStockName(),
            stock.getAddress(),
            formatter.format(stock.getDateAvailable()),
            stock.getNote()
        });
    }
}

private void showError(Exception exception) {
    JOptionPane.showMessageDialog(
            this,
            exception.getMessage(),
            "Database error",
            JOptionPane.ERROR_MESSAGE
    );
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateDatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateDatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateDatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateDatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateDatabaseFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateDatabase;
    private javax.swing.JButton btnCreateTable;
    private javax.swing.JButton btnDisplayData;
    private javax.swing.JButton btnInsertData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStocks;
    // End of variables declaration//GEN-END:variables
}
